const mongoose = require("mongoose")
const quizSchema = mongoose.Schema({
   
    subject_id:{
        type:Number,
        //required:true
    },
    admin_id:{
        type:Number,
        //required:true
    },
    qp_title:{
        type:String,
        //required:true
    },
    qp_image:{
        type:String,
        //required:true
    },
    qp_ans_value:{
        type:Number,
        //required:true
    },
    qp_type:{
        type:String,
        //required:true
    },
    qp_option1:{
        type:String,
        //required:true
    },
    qp_option2:{
        type:String,
        //required:true
    },
    qp_option3:{
        type:String,
        //required:true
    },
    qp_option4:{
        type:String,
        //required:true
    },
    qp_text:{
        type:String,
        //required:true
    },
    qp_status:{
        type:Number,
        //required:true
    },
    add_date:{
        type:Date,
        //required:true
    }
})
module.exports = mongoose.model("Quiz", quizSchema)